version: 2.1
orbs:
  windows: circleci/windows@2.2.0
workflows:
  test-env-vars:
    jobs:
      - build:
          context: my_context
jobs:
  build:
    executor:
      name: windows/default 	
    steps:
       - checkout
       - run:
           name: "echo environment variables from my_context context"
           command: echo $my_token
             
            
    
            
