version: 2.1
orbs:
  windows: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: windows/default 	
    
    steps:
       - checkout
       - run:
           command: |
             
             git clone https://github.com/dotnet/samples.git
             cd samples
             dotnet.exe build --configuration Release
