version: 2.1
orbs:
  windows: circleci/windows@2.2.0
workflows:
  test-env-vars:
    jobs:
      - build:
          context: my_context
jobs:
  build:
    executor:
      name: windows/default 	
    steps:
       - checkout
       - run:
          environment:
              my_token: $my_token
          name: "github"
          command: git clone https://12345naga:$env:my_token@github.com/12345naga/node.git
            
