version: 2.1
orbs:
  windows: circleci/windows@2.2.0
workflows:
  build:
    jobs:
      - build:
         context: github
jobs:
  build:
    executor:
      name: windows/default 	
    working_directory: ~/project1
    steps:
       - checkout
       - run: echo $my_token
          
           
           
             
            
    
            
