version: 2.1
orbs:
  windows: circleci/windows@2.2.0
workflows:
  test-env-vars:
    jobs:
      - build
jobs:
  build:
    executor:
      name: windows/default 	
    working_directory: ~/project1
    steps:
       - checkout
       - run:
           command: |
              echo pass="$token" >> "${BASH_ENV}"
       - run:
           command: |
              echo $pass
           
             
            
    
            
